# Generated by Django 5.2 on 2025-04-25 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0002_categoriamateriaprima'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la materia prima.', max_length=50, unique=True, verbose_name='Código MP')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre MP')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Nivel mínimo deseado en inventario.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, help_text='Nivel máximo deseado en inventario.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Stock Máximo')),
                ('tiempo_entrega_std_dias', models.PositiveIntegerField(default=0, help_text='Tiempo estándar en días desde el pedido hasta la recepción.', verbose_name='Lead Time Estándar (días)')),
                ('requiere_lote', models.BooleanField(default=True, help_text='Indica si el inventario se maneja por lotes específicos.', verbose_name='¿Requiere Lote?')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.categoriamateriaprima', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.proveedor', verbose_name='Proveedor Preferido')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.unidadmedida', verbose_name='Unidad de Medida Inventario')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'ordering': ['codigo'],
            },
        ),
    ]
