# Generated by Django 5.2 on 2025-04-25 13:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_ubicacion'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0001_initial'),
        ('produccion', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.CharField(db_index=True, help_text='Identificador único del lote físico en inventario.', max_length=100, unique=True, verbose_name='ID Lote/Rollo/Paleta')),
                ('cantidad_actual', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cantidad Actual')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('CUARENTENA', 'En Cuarentena'), ('BLOQUEADO', 'Bloqueado'), ('CONSUMIDO', 'Consumido'), ('DESPACHADO', 'Despachado'), ('DESECHADO', 'Desechado/Scrap')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado Lote')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cantidad Recibida')),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Recepción')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('documento_recepcion', models.CharField(blank=True, max_length=100, verbose_name='Documento Recepción')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Costo Unitario Lote')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.materiaprima')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.proveedor', verbose_name='Proveedor')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.ubicacion', verbose_name='Ubicación Actual')),
            ],
            options={
                'verbose_name': 'Lote Materia Prima',
                'verbose_name_plural': 'Lotes Materia Prima',
                'ordering': ['-creado_en', 'lote_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteProductoEnProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.CharField(db_index=True, help_text='Identificador único del lote físico en inventario.', max_length=100, unique=True, verbose_name='ID Lote/Rollo/Paleta')),
                ('cantidad_actual', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cantidad Actual')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('CUARENTENA', 'En Cuarentena'), ('BLOQUEADO', 'Bloqueado'), ('CONSUMIDO', 'Consumido'), ('DESPACHADO', 'Despachado'), ('DESECHADO', 'Desechado/Scrap')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado Lote')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proceso_origen_object_id', models.PositiveIntegerField()),
                ('cantidad_producida_primaria', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cant. Producida (Unidad Primaria)')),
                ('cantidad_producida_secundaria', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cant. Producida (Unidad Secundaria)')),
                ('fecha_produccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_wip_producidos', to='produccion.ordenproduccion')),
                ('proceso_origen_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_wip', to='productos.productoterminado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.ubicacion', verbose_name='Ubicación Actual')),
                ('unidad_medida_primaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuracion.unidadmedida')),
                ('unidad_medida_secundaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuracion.unidadmedida')),
            ],
            options={
                'verbose_name': 'Lote Producto en Proceso',
                'verbose_name_plural': 'Lotes Producto en Proceso',
                'ordering': ['-creado_en', 'lote_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoteProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_id', models.CharField(db_index=True, help_text='Identificador único del lote físico en inventario.', max_length=100, unique=True, verbose_name='ID Lote/Rollo/Paleta')),
                ('cantidad_actual', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cantidad Actual')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('CUARENTENA', 'En Cuarentena'), ('BLOQUEADO', 'Bloqueado'), ('CONSUMIDO', 'Consumido'), ('DESPACHADO', 'Despachado'), ('DESECHADO', 'Desechado/Scrap')], db_index=True, default='DISPONIBLE', max_length=20, verbose_name='Estado Lote')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proceso_final_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_producida', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Cantidad Producida')),
                ('fecha_produccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pt_producidos', to='produccion.ordenproduccion')),
                ('proceso_final_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pt', to='productos.productoterminado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.ubicacion', verbose_name='Ubicación Actual')),
            ],
            options={
                'verbose_name': 'Lote Producto Terminado',
                'verbose_name_plural': 'Lotes Producto Terminado',
                'ordering': ['-creado_en', 'lote_id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Fecha y Hora')),
                ('tipo_movimiento', models.CharField(choices=[('RECEPCION_MP', 'Recepción Materia Prima'), ('PRODUCCION_WIP', 'Producción Producto en Proceso'), ('PRODUCCION_PT', 'Producción Producto Terminado'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('TRANSFERENCIA_ENTRADA', 'Entrada por Transferencia'), ('QA_RELEASE', 'Liberación de Calidad'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('CONSUMO_MP', 'Consumo Materia Prima'), ('CONSUMO_WIP', 'Consumo Producto en Proceso'), ('ENVIO_PT', 'Envío Producto Terminado'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('TRANSFERENCIA_SALIDA', 'Salida por Transferencia'), ('QA_HOLD', 'Bloqueo por Calidad'), ('DESECHO_SCRAP', 'Desecho / Scrap'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor')], max_length=30, verbose_name='Tipo Movimiento')),
                ('lote_object_id', models.PositiveIntegerField(db_index=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad Movida')),
                ('documento_referencia', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Documento Referencia')),
                ('proceso_referencia_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('lote_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='contenttypes.contenttype')),
                ('proceso_referencia_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='configuracion.ubicacion', verbose_name='Ubicación Destino')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='configuracion.ubicacion', verbose_name='Ubicación Origen')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.unidadmedida', verbose_name='Unidad de Medida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['lote_content_type', 'lote_object_id', '-timestamp'], name='inventario__lote_co_306477_idx'), models.Index(fields=['tipo_movimiento', '-timestamp'], name='inventario__tipo_mo_af94ca_idx'), models.Index(fields=['documento_referencia'], name='inventario__documen_55c2bc_idx')],
            },
        ),
    ]
