# Generated by Django 5.2 on 2025-04-25 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_ubicacion'),
        ('inventario', '0002_lotemateriaprima_loteproductoenproceso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código único de la tinta.', max_length=50, unique=True, verbose_name='Código Tinta')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Descriptivo')),
                ('color_exacto', models.CharField(blank=True, max_length=50, verbose_name='Color / Pantone')),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('referencia_fabricante', models.CharField(blank=True, max_length=100)),
                ('requiere_lote', models.BooleanField(default=True, help_text='Indica si el inventario se maneja por lotes específicos.', verbose_name='¿Requiere Lote?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_tinta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.tipotinta', verbose_name='Tipo de Tinta')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Tinta',
                'verbose_name_plural': 'Tintas',
                'ordering': ['codigo'],
            },
        ),
    ]
