# Generated by Django 5.2 on 2025-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_tinta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='documento_referencia',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Documento Referencia'),
        ),
    ]
