# Generated by Django 5.2 on 2025-04-25 17:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0004_alter_movimientoinventario_documento_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemateriaprima',
            name='lote_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Lote/Rollo/Paleta'),
        ),
        migrations.AlterField(
            model_name='loteproductoenproceso',
            name='cantidad_producida_primaria',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cant. Producida (Unidad Primaria)'),
        ),
        migrations.AlterField(
            model_name='loteproductoenproceso',
            name='cantidad_producida_secundaria',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Cant. Producida (Unidad Secundaria)'),
        ),
        migrations.AlterField(
            model_name='loteproductoenproceso',
            name='lote_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Lote/Rollo/Paleta'),
        ),
        migrations.AlterField(
            model_name='loteproductoterminado',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad Producida'),
        ),
        migrations.AlterField(
            model_name='loteproductoterminado',
            name='lote_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Lote/Rollo/Paleta'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='tiempo_entrega_std_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Lead Time Estándar (días)'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='lote_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
