# Generated by Django 5.2 on 2025-04-27 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_lotemateriaprima_lote_id_and_more'),
        ('produccion', '0007_remove_doblado_kg_producidos_reportados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemateriaprima',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, help_text='OP a la que se reservó este lote (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_mp_asignados', to='produccion.ordenproduccion'),
        ),
    ]
