service: arcopack
runtime: python39

entrypoint: gunicorn -b :$PORT erp_config.wsgi:application

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80

env_variables:
  DJANGO_DEBUG: 'False'
  DJANGO_SETTINGS_MODULE: 'erp_config.settings'
  DATABASE_ENGINE: 'django.db.backends.postgresql'
  DATABASE_NAME: 'arcopackdb'
  DATABASE_USER: 'arcopackuser'
  # Usar Secret Manager para credenciales sensibles en producción
  DATABASE_PASSWORD: 'ArcopakDB2025!'
  DATABASE_HOST: '/cloudsql/appsindunnova:southamerica-east1:arcopack-db'
  DATABASE_PORT: ''
  DJANGO_SECRET_KEY: 'django-production-secret-key-change-this-in-production'
  PYTHONUNBUFFERED: '1'
  GOOGLE_CLOUD_PROJECT: 'appsindunnova'

beta_settings:
  cloud_sql_instances: appsindunnova:southamerica-east1:arcopack-db

handlers:
  - url: /static
    static_dir: staticfiles/
    expiration: 1d

  - url: /media
    static_dir: media/
    expiration: 1d

  - url: /.*
    script: auto

network:
  session_affinity: true