# Generated by Django 4.2.21 on 2025-05-26 17:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_remove_productoterminado_categoria_and_more'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(db_index=True, help_text='Número único del pedido', max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Pedido')),
                ('fecha_compromiso', models.DateField(help_text='Fecha comprometida con el cliente', verbose_name='Fecha Compromiso de Entrega')),
                ('fecha_entrega_estimada', models.DateField(blank=True, help_text='Fecha estimada interna de entrega', null=True, verbose_name='Fecha Entrega Estimada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Real')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En Producción'), ('PRODUCIDO', 'Producido'), ('PENDIENTE_FACTURAR', 'Pendiente por Facturar'), ('FACTURADO', 'Facturado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado del Pedido')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridad')),
                ('pedido_cliente_referencia', models.CharField(blank=True, help_text='Número de pedido o referencia del cliente', max_length=100, verbose_name='Referencia del Cliente')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, verbose_name='Condiciones de Pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor Total')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Facturación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido', '-numero_pedido'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En Producción'), ('PRODUCIDO', 'Producido'), ('PENDIENTE_FACTURAR', 'Pendiente por Facturar'), ('FACTURADO', 'Facturado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En Producción'), ('PRODUCIDO', 'Producido'), ('PENDIENTE_FACTURAR', 'Pendiente por Facturar'), ('FACTURADO', 'Facturado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Cambio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Cambio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pedidos.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Pedido',
                'verbose_name_plural': 'Seguimientos de Pedidos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad Solicitada')),
                ('cantidad_producida', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Cantidad Producida')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Precio Unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento (%)')),
                ('especificaciones_tecnicas', models.TextField(blank=True, help_text='Detalles técnicos específicos para esta línea', verbose_name='Especificaciones Técnicas')),
                ('fecha_entrega_requerida', models.DateField(blank=True, help_text='Fecha específica requerida para esta línea', null=True, verbose_name='Fecha Entrega Requerida')),
                ('orden_linea', models.PositiveIntegerField(default=1, verbose_name='Orden en Pedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productoterminado', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
                'ordering': ['pedido', 'orden_linea'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'fecha_compromiso'], name='pedidos_ped_estado_98b674_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'estado'], name='pedidos_ped_cliente_92f889_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lineapedido',
            unique_together={('pedido', 'producto', 'orden_linea')},
        ),
    ]
