# Generated by Django 5.2 on 2025-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_categoriamateriaprima'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Ubicación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Ubicación')),
                ('tipo', models.CharField(choices=[('BODEGA_MP', 'Bodega Materia Prima'), ('BODEGA_PT', 'Bodega Producto Terminado'), ('BODEGA_WIP', 'Bodega Producto en Proceso'), ('PISO_PROD', 'Piso Producción'), ('BUFFER_PROD', 'Buffer Intermedio Producción'), ('CALIDAD', 'Área de Calidad'), ('DESPACHO', 'Área de Despacho'), ('OBSOLETOS', 'Área de Obsoletos'), ('EXTERNO', 'Ubicación Externa'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['codigo'],
            },
        ),
    ]
