# Generated by Django 4.2.21 on 2025-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_alter_categoriamateriaprima_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('LAMINA', 'Lámina'), ('BOLSA', 'Bolsa')], max_length=20, unique=True, verbose_name='SubLínea')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SubLínea',
                'verbose_name_plural': 'SubLíneas',
                'ordering': ['nombre'],
            },
        ),
    ]
