# Generated by Django 4.2.21 on 2025-06-02 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_sublinea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lamina',
            options={'ordering': ['codigo'], 'verbose_name': 'Tipo de Lámina', 'verbose_name_plural': 'Tipos de Lámina'},
        ),
        migrations.AddField(
            model_name='lamina',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='lamina',
            name='codigo',
            field=models.CharField(default='PENDIENTE', max_length=100, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='lamina',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='lamina',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='lamina',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lamina',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
