# Generated by Django 5.2 on 2025-04-25 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('configuracion', '0002_categoriamateriaprima'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_numero', models.CharField(db_index=True, help_text='Identificador único de la Orden de Producción.', max_length=50, unique=True, verbose_name='No. Orden Producción (OP)')),
                ('pedido_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pedido Cliente No.')),
                ('id_pedido_contable', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID Pedido Contable')),
                ('cantidad_solicitada_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad Solicitada (Kg)')),
                ('cantidad_producida_kg', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad Producida Acumulada (Kg)')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Creación OP')),
                ('fecha_compromiso_entrega', models.DateField(verbose_name='Fecha Compromiso Entrega')),
                ('fecha_estimada_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada Inicio Prod.')),
                ('fecha_real_inicio', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Real Inicio Prod.')),
                ('fecha_real_terminacion', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Real Terminación Prod.')),
                ('fecha_real_entrega', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Real Entrega')),
                ('ancho_sustrato_mm', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ancho Sustrato (mm)')),
                ('calibre_sustrato_um', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Calibre Sustrato (µm)')),
                ('tratamiento_sustrato', models.CharField(blank=True, max_length=100, verbose_name='Tratamiento Sustrato')),
                ('color_sustrato', models.CharField(blank=True, max_length=50, verbose_name='Color Sustrato')),
                ('etapa_actual', models.CharField(choices=[('PLAN', 'Planeada'), ('PROG', 'Programada'), ('LIBR', 'Liberada a Producción'), ('IMPR', 'En Impresión'), ('REFI', 'En Refilado'), ('SELL', 'En Sellado'), ('DOBL', 'En Doblado'), ('PEND', 'Pendiente Calidad'), ('TERM', 'Terminada'), ('CTOTAL', 'Cerrada Total'), ('CPARC', 'Cerrada Parcial'), ('ANUL', 'Anulada')], db_index=True, default='PLAN', max_length=10, verbose_name='Etapa Actual')),
                ('codigo_barras_op', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras OP')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('observaciones_produccion', models.TextField(blank=True, verbose_name='Observaciones de Producción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la OP no está anulada.', verbose_name='Activa')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_creadas', to=settings.AUTH_USER_MODEL)),
                ('procesos', models.ManyToManyField(help_text='Seleccione los procesos por los que debe pasar esta OP.', to='configuracion.proceso', verbose_name='Procesos Requeridos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.productoterminado', verbose_name='Producto Terminado (Referencia)')),
                ('sustrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.materiaprima', verbose_name='Sustrato Principal')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion', 'op_numero'],
            },
        ),
    ]
