# Generated by Django 5.2 on 2025-04-25 14:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_ubicacion'),
        ('personal', '0001_initial'),
        ('produccion', '0002_doblado_parodoblado_refilado_parorefilado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parodoblado',
            options={'ordering': ['hora_inicio_paro'], 'verbose_name': 'Paro de Doblado', 'verbose_name_plural': 'Paros de Doblado'},
        ),
        migrations.AddField(
            model_name='doblado',
            name='kg_producidos_reportados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kg totales de WIP/PT producidos en esta corrida (entrada manual).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Kg Producidos Reportados'),
        ),
        migrations.AddField(
            model_name='refilado',
            name='kg_producidos_reportados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kg totales de WIP producidos en esta corrida (entrada manual).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Kg Producidos Reportados'),
        ),
        migrations.AddField(
            model_name='registroimpresion',
            name='kg_producidos_reportados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kg totales de WIP producidos en esta corrida (entrada manual).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Kg Producidos Reportados'),
        ),
        migrations.AddField(
            model_name='sellado',
            name='unidades_producidas_reportadas',
            field=models.PositiveIntegerField(default=0, help_text='Unidades totales de PT producidas en esta corrida (entrada manual).', verbose_name='Unidades Producidas Reportadas'),
        ),
        migrations.AlterField(
            model_name='doblado',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doblado',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='ancho_sustrato_mm',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ancho Sustrato (mm)'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_solicitada_kg',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Solicitada (Kg)'),
        ),
        migrations.AlterField(
            model_name='registroimpresion',
            name='aprobado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresiones_aprobadas', to='personal.colaborador'),
        ),
        migrations.AlterField(
            model_name='registroimpresion',
            name='maquina',
            field=models.ForeignKey(limit_choices_to={'tipo': 'IMPRESORA'}, on_delete=django.db.models.deletion.PROTECT, to='configuracion.maquina'),
        ),
        migrations.AlterField(
            model_name='registroimpresion',
            name='operario_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresiones_operadas', to='personal.colaborador'),
        ),
        migrations.AlterField(
            model_name='registroimpresion',
            name='orden_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_impresion', to='produccion.ordenproduccion'),
        ),
        migrations.AlterField(
            model_name='sellado',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellado',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DesperdicioDoblado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_desperdicio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desperdicios_doblado', to='produccion.doblado')),
                ('tipo_desperdicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.tipodesperdicio')),
            ],
            options={
                'verbose_name': 'Desperdicio de Doblado',
                'verbose_name_plural': 'Desperdicios de Doblado',
            },
        ),
    ]
