# Generated by Django 5.2 on 2025-04-25 15:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_tinta'),
        ('produccion', '0003_alter_parodoblado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoSustratoImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida (Kg)')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lotemateriaprima', verbose_name='Lote Sustrato Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_impresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_sustrato', to='produccion.registroimpresion')),
            ],
            options={
                'verbose_name': 'Consumo Sustrato (Impresión)',
                'verbose_name_plural': 'Consumos Sustrato (Impresión)',
                'unique_together': {('registro_impresion', 'lote_consumido')},
            },
        ),
    ]
