# Generated by Django 5.2 on 2025-04-25 15:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimientoinventario_documento_referencia'),
        ('produccion', '0004_consumosustratoimpresion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoWipDoblado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida (Kg)')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.loteproductoenproceso', verbose_name='Lote WIP Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_doblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_wip', to='produccion.doblado')),
            ],
            options={
                'verbose_name': 'Consumo WIP (Doblado)',
                'verbose_name_plural': 'Consumos WIP (Doblado)',
                'unique_together': {('registro_doblado', 'lote_consumido')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoWipRefilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida (Kg)')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.loteproductoenproceso', verbose_name='Lote WIP Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_refilado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_wip', to='produccion.refilado')),
            ],
            options={
                'verbose_name': 'Consumo WIP (Refilado)',
                'verbose_name_plural': 'Consumos WIP (Refilado)',
                'unique_together': {('registro_refilado', 'lote_consumido')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoWipSellado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida (Kg)')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.loteproductoenproceso', verbose_name='Lote WIP Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_sellado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_wip', to='produccion.sellado')),
            ],
            options={
                'verbose_name': 'Consumo WIP (Sellado)',
                'verbose_name_plural': 'Consumos WIP (Sellado)',
                'unique_together': {('registro_sellado', 'lote_consumido')},
            },
        ),
    ]
