# Generated by Django 5.2 on 2025-04-25 17:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_lotemateriaprima_lote_id_and_more'),
        ('produccion', '0005_consumowipdoblado_consumowiprefilado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimpresion',
            name='produccion_registrada_en_inventario',
            field=models.BooleanField(default=False, editable=False, verbose_name='¿Producción registrada en inventario?'),
        ),
        migrations.AlterField(
            model_name='consumosustratoimpresion',
            name='lote_consumido',
            field=models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotemateriaprima', verbose_name='Lote Sustrato Consumido'),
        ),
        migrations.CreateModel(
            name='ConsumoMpDoblado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotemateriaprima', verbose_name='Lote MP Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_doblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_mp', to='produccion.doblado')),
            ],
            options={
                'verbose_name': 'Consumo MP (Doblado)',
                'verbose_name_plural': 'Consumos MP (Doblado)',
                'unique_together': {('registro_doblado', 'lote_consumido')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoMpRefilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotemateriaprima', verbose_name='Lote MP Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_refilado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_mp', to='produccion.refilado')),
            ],
            options={
                'verbose_name': 'Consumo MP (Refilado)',
                'verbose_name_plural': 'Consumos MP (Refilado)',
                'unique_together': {('registro_refilado', 'lote_consumido')},
            },
        ),
        migrations.CreateModel(
            name='ConsumoMpSellado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad Consumida')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('lote_consumido', models.ForeignKey(limit_choices_to={'estado': 'DISPONIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.lotemateriaprima', verbose_name='Lote MP Consumido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro_sellado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_mp', to='produccion.sellado')),
            ],
            options={
                'verbose_name': 'Consumo MP (Sellado)',
                'verbose_name_plural': 'Consumos MP (Sellado)',
                'unique_together': {('registro_sellado', 'lote_consumido')},
            },
        ),
    ]
