# Generated by Django 5.2 on 2025-04-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_registroimpresion_produccion_registrada_en_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doblado',
            name='kg_producidos_reportados',
        ),
        migrations.RemoveField(
            model_name='refilado',
            name='kg_producidos_reportados',
        ),
        migrations.RemoveField(
            model_name='registroimpresion',
            name='kg_producidos_reportados',
        ),
        migrations.RemoveField(
            model_name='registroimpresion',
            name='produccion_registrada_en_inventario',
        ),
        migrations.RemoveField(
            model_name='sellado',
            name='unidades_producidas_reportadas',
        ),
    ]
