# Generated by Django 5.2 on 2025-04-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_alter_categoriamateriaprima_options_and_more'),
        ('produccion', '0007_remove_doblado_kg_producidos_reportados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveIntegerField(help_text='Orden/secuencia del proceso en la OP (1=primero, 2=segundo, ...)')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_secuencia', to='produccion.ordenproduccion')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.proceso')),
            ],
            options={
                'verbose_name': 'Secuencia de Proceso en OP',
                'verbose_name_plural': 'Secuencias de Procesos en OP',
                'ordering': ['orden_produccion', 'secuencia'],
                'unique_together': {('orden_produccion', 'proceso')},
            },
        ),
    ]
