# Generated by Django 5.2 on 2025-04-27 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_lotemateriaprima_orden_produccion'),
        ('produccion', '0008_ordenproduccionproceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroimpresion',
            name='lote_wip_asociado',
            field=models.ForeignKey(blank=True, help_text='Solo lotes WIP disponibles y de la misma OP', limit_choices_to={'estado': 'DISPONIBLE'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.loteproductoenproceso', verbose_name='Lote WIP Asociado'),
        ),
    ]
