# Generated by Django 4.2.21 on 2025-05-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_registroimpresion_lote_wip_asociado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumompdoblado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumomprefilado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumompsellado',
            unique_together=set(),
        ),
    ]
