# Generated by Django 4.2.21 on 2025-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_consumompdoblado_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Información adicional relevante sobre la orden de producción', verbose_name='Observaciones'),
        ),
    ]
