# Generated by Django 4.2.21 on 2025-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_add_observaciones_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumowipdoblado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumowiprefilado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumowipsellado',
            unique_together=set(),
        ),
    ]
