# Generated by Django 4.2.21 on 2025-05-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_productoterminado_dob_medida_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminado',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente para el cual se fabrica este producto terminado', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
