# Generated by Django 4.2.21 on 2025-05-26 15:44

from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_sublinea'),
        ('productos', '0003_productoterminado_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoterminado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='comercializable',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='extrusion_doble',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='imp_rodillo',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='lamina',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='programa_lamina',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo relacionado con el producto (especificaciones, planos, etc.)', null=True, upload_to=productos.models.upload_producto_path, verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configuracion.categoriaproducto', verbose_name='Línea'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='sublinea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.sublinea', verbose_name='SubLínea'),
        ),
    ]
