# Generated by Django 5.2 on 2025-04-25 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(db_index=True, help_text='Número de Identificación Tributaria u otro documento oficial.', max_length=20, unique=True, verbose_name='NIT / Documento ID')),
                ('codigo_cliente', models.CharField(blank=True, help_text='Código interno o del sistema externo.', max_length=50, null=True, unique=True, verbose_name='Código Cliente')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('direccion_principal', models.CharField(blank=True, max_length=255, verbose_name='Dirección Principal')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Colombia', max_length=100)),
                ('telefono_principal', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Principal')),
                ('email_principal', models.EmailField(blank=True, max_length=254, verbose_name='Email Principal')),
                ('nombre_contacto_principal', models.CharField(blank=True, max_length=150, verbose_name='Contacto Principal')),
                ('email_contacto_principal', models.EmailField(blank=True, max_length=254, verbose_name='Email Contacto Principal')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, verbose_name='Condiciones de Pago')),
                ('cupo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Cupo de Crédito')),
                ('origen_datos', models.CharField(choices=[('MANUAL', 'Registro Manual'), ('API', 'Sincronizado desde API Externa')], default='MANUAL', max_length=10, verbose_name='Origen del Registro')),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID Sistema Externo')),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Sincronización API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
    ]
